# Generated by Django 5.2.1 on 2025-06-03 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('site_AMAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidade',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('horario', models.CharField(max_length=50)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('sala', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('realizado', 'Realizado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='Confirmado', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
