# Generated by Django 5.2.1 on 2025-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_AMAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='local',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidade',
            name='sala',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
