# Generated by Django 5.2.1 on 2025-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_AMAR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estagiario',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profissional',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
