# Generated by Django 5.2.1 on 2025-06-10 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_AMAR', '0002_agendamento_disponibilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag_png', models.ImageField(upload_to='imagens/')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('publicacao', models.CharField(blank=True, max_length=150)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foruns_criados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MensagemForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='site_AMAR.forums')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCurtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='site_AMAR.forums')),
            ],
            options={
                'unique_together': {('forum', 'usuario')},
            },
        ),
    ]
