# Generated by Django 5.2.1 on 2025-06-10 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_AMAR', '0003_usuario_foto_perfil_forums_mensagemforum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forums',
            name='imag_png',
        ),
    ]
