# Generated by Django 5.2.1 on 2025-06-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_AMAR', '0004_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
